[manager]
show_hidden = true
show_symlink = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
view = [
	{ run = 'mupdf "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
prepend_rules = [
	{ name = "*.json", use = "edit" },

	# Multiple openers for a single rule
	{ name = "*.html", use = [ "open", "edit" ] },
]
append_rules = [
	{ name = "*", use = "my-fallback" },
]
