return {
	welcome = {
		[[ ███▄    █ ▓█████  ▒█████   ██▒   █▓ ██▓ ███▄ ▄███▓]],
		[[ ██ ▀█   █ ▓█   ▀ ▒██▒  ██▒▓██░   █▒▓██▒▓██▒▀█▀ ██▒]],
		[[▓██  ▀█ ██▒▒███   ▒██░  ██▒ ▓██  █▒░▒██▒▓██    ▓██░]],
		[[▓██▒  ▐▌██▒▒▓█  ▄ ▒██   ██░  ▒██ █░░░██░▒██    ▒██ ]],
		[[▒██░   ▓██░░▒████▒░ ████▓▒░   ▒▀█░  ░██░▒██▒   ░██▒]],
		[[░ ▒░   ▒ ▒ ░░ ▒░ ░░ ▒░▒░▒░    ░ ▐░  ░▓  ░ ▒░   ░  ░]],
		[[░ ░░   ░ ▒░ ░ ░  ░  ░ ▒ ▒░    ░ ░░   ▒ ░░  ░      ░]],
		[[   ░   ░ ░    ░   ░ ░ ░ ▒       ░░   ▒ ░░      ░   ]],
		[[         ░    ░  ░    ░ ░        ░   ░         ░   ]],
	},
	lsp = {
		diagnostics = {
			DiagnosticSignError = " ",
			DiagnosticSignWarn = " ",
			DiagnosticSignHint = " ",
			DiagnosticSignInfo = " ",
		},
		kind = {
			-- Text = "  ",
			Text = "",
			Function = "󰊕",
			Constructor = "󰠱",
			Property = "",
			Value = "",
			Reference = "󱞱",
			Method = "  ",
			Field = "  ",
			Variable = "  ",
			Class = "  ",
			Interface = "  ",
			Module = "  ",
			Unit = "  ",
			Enum = "  ",
			Keyword = "  ",
			Snippet = "  ",
			Color = "  ",
			File = "  ",
			Folder = "  ",
			EnumMember = "  ",
			Constant = "  ",
			Struct = "  ",
			Event = "  ",
			Operator = "  ",
			TypeParameter = "  ",
		},
		menu = {
			buffer = "",
			nvim_lsp = "󰯂",
			luasnip = "",
			nvim_lua = "",
			latex_symbols = "󰬓",
		},
	},
}
